class User {
  final int? id; // Assuming 'id' is auto-generated by the database
  late final String username;
  final String password;
  final String imageUrl;

  User(
      {this.id,
      required this.username,
      required this.password,
      required this.imageUrl});

  // Convert a User into a Map. The keys must correspond to the names of the
  // columns in the database.
  Map<String, dynamic> toMap() {
    return {
      'id': id, // This will be null if a new user is being added
      'username': username,
      'password': password, // In a real app, ensure this is hashed
    };
  }

  // Implement a method to create a User from a map
  static User fromMap(Map<String, dynamic> map) {
    return User(
        id: map['id'],
        username: map['username'],
        password: map['password'],
        imageUrl:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShN0nuLT7HIpIANuDi6wbMKpeuCgZsl2PtAA&usqp=CAU");
  }

  @override
  String toString() {
    return 'User{id: $id, username: $username, password: $password, imageUrl:$imageUrl}';
  }
}
